services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: phoenix_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
     - .env
    environment:
      DATABASE_URL: "postgres://postgres:mysecretpassword@db/phoenix_db"
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  postgres_data:
